### ISSUE TITLE
Examples of ALTER TABLE with ExecuteSQL

### ISSUE THREAD

**Issue by toddgeist** [nickorr/BaseElements-Plugin#84]
I am attempting to add a field to a FileMaker table using the SQL, but I am not getting anywhere. No errors, but no new field either. I must have the syntax wrong.  Does anybody have any examples of working DDL query with ALTER TABLE?

here is what I am trying
```
ALTER TABLE "Products"
ADD "Products"."newField" varchar
```

**Comment by nilswald** [comment]
Leave out the table in the column name. This works for me:
BE_FileMakerSQL ( "alter table untitled add new_column varchar"; ""; ""; "" )

If you are experiencing problems within script, may be this could be helpful:
http://wiki.myfmbutler.com/index.php/DoSQL_2#Modifying_schema:_the_CREATE.2C_ALTER_and_DROP_statements

I am not sure, how BE handles this issue. @nickorr ?

Nils

**Comment by dansmith65** [comment]
Nils beat me to it, but I'll post this link anyways...

I always use Dracoventions SQL Runner plugin for debugging SQL queries: http://www.dracoventions.com/products/2empowerFM/family/sql.php It gives a detailed description of what went wrong, and where (starting character number).

**Comment by toddgeist** [comment]
Got it thanks.  It was the quotes that were screwing me up

**Comment by dansmith65** [comment]
It seems like the plugin should return "?" and `BE_GetLastError` should return a non-zero result.

**Comment by nickorr** [comment]
DDL commands are executed during idle time rather than immediately (otherwise FM locks up… or at least did at the time the function was written). Errors from DDL commands can be obtained using BE_GetLastDDLError

	https://github.com/nickorr/BaseElements-Plugin/wiki/Functions#BE_GetLastDDLError

I've updated the wiki for the SQL function to mention this.

Cheers,
Nick
