### ISSUE TITLE
BE_ExecuteSystemCommand to run batch file

### ISSUE THREAD

**Issue by gcatnine** [nickorr/BaseElements-Plugin#86]
Dear Nick,
I would like to use this function on the server to run a batch file (pt.bat), but even on FMPro nothing happened.
The FM script is very simple:
___
Set Variable[$file; Value:"C:\Users\MyDir\pt.bat"]
Set Field[test::clip; BE_FileExists ( $file )]  // to check if FM access the file
Set Variable[$c; Value:"cmd.exe /c " & $file]
Set Field[test::Num; BE_ExecuteSystemCommand ( $c ; 0 )]
___
Then I change the script using send Event and it works:
___
Set Variable[$file; Value:"C:\Users\MyDir\pt.bat"]
Set Field[test::clip; BE_FileExists ( $file )]   // to check if FM access the file
Send Event[open document/application; File Name:“$file” ]
___
The batch file is very simple (it is to print a pdf file):
___
"C:\Program Files (x86)\Adobe\Reader 11.0\Reader\AcroRd32.exe" /t C:\Users\MyDir\Documents\MyDoc.pdf
EXIT
___
running pt.bat with a local cmd (where the FM server resides) it works with no problem.

OS: Windows 7
plugin: 3.0.0
FM both Pro and Server: 13.v5

Any suggestions?
Many thanks

**Comment by gcatnine** [comment]
Dear Nick,
I forgot to tell you that I have even tried with:
___
Set Variable[$file; Value:"C:\Users\MyDir\pt.bat"]
Set Field[test::clip; BE_FileExists ( $file )] // to check if FM access the file
Set Field[test::Num; BE_ExecuteSystemCommand ( $file ; 0 )]
___
Nothing happened.


best regards
Gianandrea

**Comment by dansmith65** [comment]
I would imagine `C:\Users\MyDir\pt.bat` isn't the actual full path to the bat file, if that assumption is correct: does your actual path contain spaces?

If so, you would need quotes around your path like:

```
Set Variable[$c; Value:"cmd.exe /c \"" & $file & "\""]
```

**Comment by gcatnine** [comment]
it is almost the real path
No spaces

**Comment by nickorr** [comment]
Gianandrea,

Thanks for your note.

I'm sorry, but technical support for the plugin is available for sponsors only : http://www.goya.com.au/baseelements/plugin/sponsors  We receive a lot of requests for support via our email and our contact pages, but we're unable to dedicate the time to answer them all.  We get multiple plugin related requests per day, and responding to them is something we either would want to do properly or not at all, and at present we don't have the time to do it properly, and still be able to help our clients, and work on our other products.

We've created the sponsorship option to give people a way to help with the development and ongoing costs of the plugin, and to also get support questions answered.

If you've got general questions you need to ask, perhaps consider something like the FileMaker Technet forums.

Thanks for your understanding.
Goya Staff

Most likely cause is permissions : https://baseelementsplugin.zendesk.com/hc/en-us/articles/203885818-File-Permissions-when-running-under-FMS
